apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        track: stable
    spec:
      containers:
        - name: hello
          image: "hello:1.0"
          ports:
            - name: http
              containerPort: 3000
        - name: nginx
          image: "nginx:1.9.14"
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]
          volumeMounts:
            - name: "nginx-frontend-conf"
              mountPath: "/etc/nginx/conf.d"
      volumes:
        - name: "nginx-proxy-conf"
          configMap:
            name: "nginx-proxy-conf"
            items:
              - key: "frontend.conf"
                path: "frontend.conf"
